version: '3.1'
services:
  #===============ms-g-utilisateur==================================
  app:
    image: ms-g-utilisateur:latest
    build:
      context: .
    container_name: app
    depends_on:
      - db
      - app3
      - app4
    ports:
      - 8089:8089
    networks:
      - mb-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/user_role
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=safietou
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #=================ms-g-bien-et-projet====================================
  app1:
    image: ms-g-bien-et-projet:latest
    build:
      context: .
    container_name: app1
    depends_on:
      - db1
      - app3
      - app4
    ports:
      - 8082:8082
    networks:
      - mb-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/bien_categorie_projet
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=safietou
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #====================ms-g-client=================================
  app2:
    image: ms-g-client:latest
    build:
      context: .
    container_name: app2
    depends_on:
      - db2
      - app3
      - app4
    ports:
      - 8088:8088
    networks:
      - mb-spring
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/gestion_client
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=safietou
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  #=============config=======================================
  app3:
    image: ms-config:latest
    build:
      context: .
    container_name: app3
    ports:
      - 8888:8888
    networks:
      - mb-spring
    environment:
      - SPRING_CLOUD_CONFIG_SERVER_GIT_URI=file:./src/main/resources/myConfig
  #================eureka======================
  app4:
    image: ms-eureka:latest
    build:
      context: .
    container_name: app4
    depends_on:
      - app3
    ports:
      - 8761:8761
    networks:
      - mb-spring
  #===============gateway==========================
  app5:
    image: ms-gateway:latest
    build:
      context: .
    container_name: app5
    depends_on:
      - app3
      - app4
    ports:
      - 9999:9999
    networks:
      - mb-spring

  #bd-ms-g-utilisateur =======================================
  db:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - mb-spring
    container_name: db
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=safietou
      - POSTGRES_DB=user_role
    #volumes: 
     # - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  #bd-ms-g-bien-et-projet =====================================
  db1:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - mb-spring
    container_name: db1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=safietou
      - POSTGRES_DB=bien_categorie_projet
    #volumes: 
      #- ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql

  # bd-ms-g-client =========================================
  db2:
    image: postgres:13.1-alpine
    restart: always
    ports:
      - 5432:5432
    networks:
      - mb-spring
    container_name: db2
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=safietou
      - POSTGRES_DB=gestion_client
    #volumes: 
      #- ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
  #========angularrrrr====================
  client:
    image: client-angular:latest
    restart: always
    ports:
      - 4000:4000
    networks:
      - mb-spring
    container_name: client
    #volumes: 
      #- ./client/src:app/src
networks:
  mb-spring: